# Generated by Django 3.1.2 on 2020-10-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201019_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='My Tournament', max_length=250),
            preserve_default=False,
        ),
    ]
