# Generated by Django 3.1.2 on 2020-10-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201030_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.IntegerField(default=-2028),
            preserve_default=False,
        ),
    ]
