# Generated by Django 3.1.2 on 2020-11-07 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_game_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.game')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
