# Generated by Django 3.1.2 on 2020-11-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_loadingscreen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(to='core.Game')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
        ),
    ]
