# Generated by Django 3.1.2 on 2020-11-09 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_tournamentround'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='LoadingScreenAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loadingscreen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loadingscreen')),
            ],
        ),
    ]
