# Generated by Django 3.1.2 on 2020-11-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201109_1402'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together={('tournament', 'team')},
        ),
    ]
