# Generated by Django 3.1.2 on 2020-11-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201109_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingscreenadmin',
            name='loadingscreen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.loadingscreen'),
        ),
        migrations.AlterUniqueTogether(
            name='loadingscreenadmin',
            unique_together=set(),
        ),
    ]
